spring.datasource.url=jdbc:postgresql://ep-polished-unit-acdg5mh2-pooler.sa-east-1.aws.neon.tech:5432/bookstack-database?sslmode=require&channel_binding=require
spring.datasource.ursename=neondb_owner
spring.datasource.password=npg_J3mSNOp0rTuD

spring.datasource.driver-class-name=org.postgresql.Driver
